name = input("Enter your name: ")
Year_of_birth = int(input("Enter your Year of birth: "))
Month_of_birth = int(input("Enter your month of birth: "))
Day_of_birth = int(input("Enter your day of birth: "))
age = (2025 - Year_of_birth)
height = float(input("Enter your height: "))
weight_lbs = float(input("Enter your weight in lbs: "))
weight_kg = (weight_lbs * 0.45)
print(f"Hi {name}")
print(f"Your date of birth is {Day_of_birth}/{Month_of_birth}/{Year_of_birth}")
print(f"You are {age} years old")
print(f"You are {height}ft in height")
print(f"You weigh {weight_kg}kg")